# Generated by Django 4.1.3 on 2022-11-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.host')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('buy_qty', models.IntegerField(blank=True, null=True)),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('buy_loc', models.CharField(default=None, max_length=255, null=True)),
                ('buy_ts', models.DateTimeField(blank=True, null=True, verbose_name='date purchased')),
                ('sell_qty', models.IntegerField(blank=True, null=True)),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('sell_loc', models.CharField(default=None, max_length=255, null=True)),
                ('sell_ts', models.DateTimeField(blank=True, null=True, verbose_name='date sold')),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.itemcategory')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.item')),
            ],
        ),
        migrations.CreateModel(
            name='SubHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.host')),
            ],
        ),
        migrations.CreateModel(
            name='StructureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.host')),
                ('subhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.subhost')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('buy_qty', models.IntegerField(blank=True, null=True)),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('buy_loc', models.CharField(default=None, max_length=255, null=True)),
                ('buy_ts', models.DateTimeField(blank=True, null=True, verbose_name='date purchased')),
                ('sell_qty', models.IntegerField(blank=True, null=True)),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('sell_loc', models.CharField(default=None, max_length=255, null=True)),
                ('sell_ts', models.DateTimeField(blank=True, null=True, verbose_name='date sold')),
                ('num_output_one', models.FloatField(blank=True, null=True)),
                ('time_output_one', models.DurationField(blank=True, null=True)),
                ('num_output_two', models.FloatField(blank=True, null=True)),
                ('time_output_two', models.DurationField(blank=True, null=True)),
                ('num_output_three', models.FloatField(blank=True, null=True)),
                ('time_output_three', models.DurationField(blank=True, null=True)),
                ('num_output_four', models.FloatField(blank=True, null=True)),
                ('time_output_four', models.DurationField(blank=True, null=True)),
                ('num_output_five', models.FloatField(blank=True, null=True)),
                ('time_output_five', models.DurationField(blank=True, null=True)),
                ('num_output_six', models.FloatField(blank=True, null=True)),
                ('time_output_six', models.DurationField(blank=True, null=True)),
                ('consume_input_one', models.FloatField(blank=True, null=True)),
                ('time_input_one', models.DurationField(blank=True, null=True)),
                ('consume_input_two', models.FloatField(blank=True, null=True)),
                ('time_input_two', models.DurationField(blank=True, null=True)),
                ('consume_input_three', models.FloatField(blank=True, null=True)),
                ('time_input_three', models.DurationField(blank=True, null=True)),
                ('consume_input_four', models.FloatField(blank=True, null=True)),
                ('time_input_four', models.DurationField(blank=True, null=True)),
                ('consume_input_five', models.FloatField(blank=True, null=True)),
                ('time_input_five', models.DurationField(blank=True, null=True)),
                ('consume_input_six', models.FloatField(blank=True, null=True)),
                ('time_input_six', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.structurecategory')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.host')),
                ('item_input_five', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_input_five', to='inventory_tracker.item')),
                ('item_input_four', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_input_four', to='inventory_tracker.item')),
                ('item_input_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_input_one', to='inventory_tracker.item')),
                ('item_input_six', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_input_six', to='inventory_tracker.item')),
                ('item_input_three', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_input_three', to='inventory_tracker.item')),
                ('item_input_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_input_two', to='inventory_tracker.item')),
                ('item_output_five', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_output_five', to='inventory_tracker.item')),
                ('item_output_four', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_output_four', to='inventory_tracker.item')),
                ('item_output_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_output_one', to='inventory_tracker.item')),
                ('item_output_six', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_output_six', to='inventory_tracker.item')),
                ('item_output_three', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_output_three', to='inventory_tracker.item')),
                ('item_output_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ete', to='inventory_tracker.item')),
            ],
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='subhost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.subhost'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.host'),
        ),
        migrations.AddField(
            model_name='item',
            name='subhost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.subhost'),
        ),
    ]
