# Generated by Django 4.1.3 on 2022-11-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_tracker', '0003_alter_subhost_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='item_category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subhost',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='subhost',
        ),
        migrations.RemoveField(
            model_name='structurecategory',
            name='subhost',
        ),
        migrations.AddField(
            model_name='transaction',
            name='structure_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.structurecategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subhost',
            field=models.ManyToManyField(to='inventory_tracker.subhost'),
        ),
    ]
