# Generated by Django 4.1.3 on 2022-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_tracker', '0006_remove_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
